<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>userphoto</name>
   <tag></tag>
   <elementGuidId>42354d2b-e46a-4203-b2ae-3a605b10ce2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;nav-content&quot;]/div/app-user-dropdown/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;nav-content&quot;]/div/app-user-dropdown/div/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
